### PR TITLE
API for feedbackmomenten

### PR DESCRIPTION
**Pull request by luttje**
This adds an API that exposes all necessary information for tracking study points.

@bartjroos can you confirm that this is the data I should use for tracking study points? If so this can merge and I'll start work on a separate app for the study points tracking.

Example output:
```json
[
    {
        "blok": "Blok O",
        "datum_start": "2023-08-01T00:00:00.000000Z",
        "datum_eind": "2024-02-01T00:00:00.000000Z",
        "vakken": [
            {
                "vak": "QUI",
                "volgorde": 0,
                "modules": [
                    {
                        "module": "YHT-I",
                        "leerlijn": "YHT",
                        "week_start": 1,
                        "week_eind": 11,
                        "feedbackmomenten": [
                            {
                                "code": "FVQ4",
                                "naam": "Hic et.",
                                "week": 4,
                                "points": 1
                            }
                        ]
                    },
                    {
                        "module": "QER-II",
                        "leerlijn": "QER",
                        "week_start": 12,
                        "week_eind": 16,
                        "feedbackmomenten": [
                            {
                                "code": "F79A",
                                "naam": "Ab quo consequatur.",
                                "week": 1,
                                "points": 5
                            }
                        ]
                    }
                ]
            },
            {
                "vak": "MOL",
                "volgorde": 5,
                "modules": [
                    {
                        "module": "QER-II",
                        "leerlijn": "QER",
                        "week_start": 1,
                        "week_eind": 13,
                        "feedbackmomenten": [
                            {
                                "code": "F79A",
                                "naam": "Ab quo consequatur.",
                                "week": 1,
                                "points": 5
                            }
                        ]
                    },
                    {
                        "module": "FKD-II",
                        "leerlijn": "FKD",
                        "week_start": 14,
                        "week_eind": 16,
                        "feedbackmomenten": [
                            {
                                "code": "FJSM",
                                "naam": "Voluptatibus sed rerum qui.",
                                "week": 2,
                                "points": 5
                            },
                            {
                                "code": "FTVW",
                                "naam": "Quis aliquam iusto.",
                                "week": 15,
                                "points": 2
                            }
                        ]
                    }
                ]
            },
            {
                "vak": "MIN",
                "volgorde": 7,
                "modules": [
                    {
                        "module": "VON-II",
                        "leerlijn": "VON",
                        "week_start": 1,
                        "week_eind": 14,
                        "feedbackmomenten": []
                    },
                    {
                        "module": "WCI-II",
                        "leerlijn": "WCI",
                        "week_start": 15,
                        "week_eind": 16,
                        "feedbackmomenten": {
                            "1": {
                                "code": "FQTV",
                                "naam": "Libero nesciunt ipsum.",
                                "week": 2,
                                "points": 6
                            },
                            "0": {
                                "code": "FBDP",
                                "naam": "Eligendi et id esse.",
                                "week": 13,
                                "points": 9
                            }
                        }
                    }
                ]
            },
            {
                "vak": "ILL",
                "volgorde": 9,
                "modules": [
                    {
                        "module": "JEM-I",
                        "leerlijn": "JEM",
                        "week_start": 1,
                        "week_eind": 10,
                        "feedbackmomenten": []
                    },
                    {
                        "module": "FKD-II",
                        "leerlijn": "FKD",
                        "week_start": 11,
                        "week_eind": 16,
                        "feedbackmomenten": [
                            {
                                "code": "F3QM",
                                "naam": "Animi dignissimos commodi optio.",
                                "week": 15,
                                "points": 10
                            },
                            {
                                "code": "FRJ4",
                                "naam": "Nisi expedita ipsam id.",
                                "week": 15,
                                "points": 4
                            }
                        ]
                    }
                ]
            }
        ]
    },
    {
        "blok": "Blok H",
        "datum_start": "2023-08-01T00:00:00.000000Z",
        "datum_eind": "2024-02-01T00:00:00.000000Z",
        "vakken": [
            {
                "vak": "COR",
                "volgorde": 4,
                "modules": [
                    {
                        "module": "YHT-II",
                        "leerlijn": "YHT",
                        "week_start": 1,
                        "week_eind": 9,
                        "feedbackmomenten": [
                            {
                                "code": "FY5T",
                                "naam": "Repudiandae nihil adipisci ad repellendus.",
                                "week": 7,
                                "points": 1
                            }
                        ]
                    },
                    {
                        "module": "QER-III",
                        "leerlijn": "QER",
                        "week_start": 10,
                        "week_eind": 16,
                        "feedbackmomenten": [
                            {
                                "code": "FAGS",
                                "naam": "Beatae ipsa ea.",
                                "week": 7,
                                "points": 3
                            }
                        ]
                    }
                ]
            },
            {
                "vak": "ENI",
                "volgorde": 6,
                "modules": [
                    {
                        "module": "VON-II",
                        "leerlijn": "VON",
                        "week_start": 1,
                        "week_eind": 8,
                        "feedbackmomenten": [
                            {
                                "code": "FH5P",
                                "naam": "Aut inventore ut voluptatem.",
                                "week": 12,
                                "points": 3
                            }
                        ]
                    },
                    {
                        "module": "DHH-I",
                        "leerlijn": "DHH",
                        "week_start": 9,
                        "week_eind": 16,
                        "feedbackmomenten": [
                            {
                                "code": "FJMP",
                                "naam": "Modi tenetur dolorem quia.",
                                "week": 10,
                                "points": 6
                            }
                        ]
                    }
                ]
            },
            {
                "vak": "EST",
                "volgorde": 7,
                "modules": [
                    {
                        "module": "UPF-II",
                        "leerlijn": "UPF",
                        "week_start": 1,
                        "week_eind": 3,
                        "feedbackmomenten": []
                    },
                    {
                        "module": "VON-I",
                        "leerlijn": "VON",
                        "week_start": 4,
                        "week_eind": 16,
                        "feedbackmomenten": []
                    }
                ]
            },
            {
                "vak": "ASS",
                "volgorde": 9,
                "modules": [
                    {
                        "module": "KCN-I",
                        "leerlijn": "KCN",
                        "week_start": 1,
                        "week_eind": 14,
                        "feedbackmomenten": []
                    },
                    {
                        "module": "KCN-III",
                        "leerlijn": "KCN",
                        "week_start": 15,
                        "week_eind": 16,
                        "feedbackmomenten": []
                    }
                ]
            }
        ]
    }
]
```

### CODE REVIEW

**Comment by luttje** [comment]
@bartjroos additional question: where should I get the `bpoints` from? I'm having trouble finding them in the live currapp, so don't really understand how I would fetch them for this API

**Comment by bartjroos** [comment]
B-points aren't stored anywhere indeed, as there are always two b-points per "vak", 

> **B-punten: beroepshouding**
> Te behalen door goede werkhouding in de les. Voor ieder vak zijn twee B-punten te halen, ongeacht de grootte/zwaarte van het vak. Aan het einde van het blok moeten 100% van de B-punten zijn behaald, maar eventueel missende punten kunnen worden gecompenseerd met C-punten.

**Comment by bartjroos** [comment]
> @bartjroos can you confirm that this is the data I should use for tracking study points? If so this can merge and I'll start work on a separate app for the study points tracking.

Seems correct!


(The CurrApp also know which cohorts are currently following a "blok". For a later iteration we might want to add this info to the API, so the new app can automatically match a "klas" to the right "blok".)

**Review by bartjroos — APPROVED** [review]

**Comment by bartjroos** [comment]
API should be available in production now!

**Pull request merged**
